import { StyleSheet } from 'react-native';

export const participantStyles = StyleSheet.create({
  container: {
    margin: 8,
    alignItems: 'flex-start',
    position: 'relative',
    flexDirection: 'column',
    width: 72,
  },

  avatarText: {
    fontSize: 16,
    color: '#fff',
  },
  audioIcon: {
    position: 'absolute',
    backgroundColor: '#1f2d3d',
    width: 32,
    height: 32,
    top: 72 - 28,
    paddingTop: 4,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 16,
  },
  menuButton: {
    backgroundColor: '#1f2d3d',
    width: 32,
    height: 32,
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 16,
    top: 72 - 28,
    padding: 0,
    right: 0,
  },
  menuContainer: {
    position: 'absolute',
    bottom: -64,
    right: -64,
    zIndex: 10,
  },
  avatar: {
    width: 72,
    height: 72,
    borderRadius: 9999,
    backgroundColor: '#2b3e56',
    alignItems: 'center',
    justifyContent: 'center',
  },
  name: {
    color: '#fff',
    marginVertical: 4,
    fontWeight: '400',
    paddingTop: 8,
    fontSize: 12,
    width: 72,
    textAlign: 'center',
    lineHeight: 12,
  },
  role: {
    color: '#c8d1dc',
    marginVertical: 4,
    fontWeight: '400',
    fontSize: 12,
    width: 72,
    textAlign: 'center',
    lineHeight: 12,
  },
  initials: {
    fontSize: 16,
    color: '#fff',
    lineHeight: 32,
  },
  isActive: {
    borderColor: 'green',
    borderWidth: 2,
  },
  isMuted: {
    backgroundColor: '#2b3e56',
  },
  showMore: {
    backgroundColor: "white",
    padding: 4,
    borderRadius: 24,
    position: 'absolute',
    top: -50,
    right: -6,
  },
  menu: {
    position: 'absolute',
    top: 72 - 28,
    right: -4,
    backgroundColor: "#1f2d3d",
    padding: 4,
    borderRadius: 16,
    shadowOffset: {
      height: 1,
      width: 1,
    },
  },
});
