import { StyleSheet } from 'react-native';

export const getParticipantStyles = (textColor, avatarColor, buttonIconColors) => StyleSheet.create({
  anchor: {
    backgroundColor: buttonIconColors,
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 16,
    top: 44, 
    right: 16, 
    zIndex: 15,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.10)",
  },
  menuModal: {
    backgroundColor: buttonIconColors,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 8,
    padding: 32,
    minWidth: 175
  },
  menuItem: {
    padding: 10,
  },
  menuItemText: {
    color: textColor,
  },
  container: {
    margin: 8,
    alignItems: 'flex-start',
    position: 'relative',
    flexDirection: 'column',
    width: 72,
  },

  avatarText: {
    fontSize: 16,
    color: textColor,
  },
  audioIcon: {
    position: 'absolute',
    backgroundColor: buttonIconColors,
    width: 32,
    height: 32,
    top: 72 - 28,
    paddingTop: 4,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 16,
  },
  menuButton: {
    backgroundColor: buttonIconColors,
    width: 32,
    height: 32,
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 16,
    top: 72 - 28,
    padding: 0,
    right: -4,
  },
  menuContainer: {
    position: 'absolute',
    bottom: -64,
    right: -64,
    zIndex: 10,
  },
  avatar: {
    width: 72,
    height: 72,
    borderRadius: 9999,
    backgroundColor: avatarColor,
    alignItems: 'center',
    justifyContent: 'center',
  },
  name: {
    color: textColor,
    marginVertical: 4,
    fontWeight: '400',
    paddingTop: 8,
    fontSize: 12,
    width: 72,
    textAlign: 'center',
    lineHeight: 16,
  },
  role: {
    color: '#c8d1dc',
    marginVertical: 4,
    fontWeight: '400',
    fontSize: 12,
    width: 72,
    textAlign: 'center',
    lineHeight: 16,
  },
  initials: {
    fontSize: 16,
    color: textColor,
    lineHeight: 32,
  },
  isActive: {
    borderColor: 'green',
    borderWidth: 2,
  },
  isMuted: {
    backgroundColor: avatarColor,
  },
  showMore: {
    backgroundColor: textColor,
    padding: 4,
    borderRadius: 24,
    position: 'absolute',
    top: -50,
    right: -6,
  },
  menu: {
    position: 'absolute',
    top: 72 - 28,
    right: -4,
    backgroundColor: buttonIconColors,
    padding: 4,
    borderRadius: 16,
    shadowOffset: {
      height: 1,
      width: 1,
    },
  },
});
